---
kind: pipeline
type: docker
name: container

platform:
  os: linux
  arch: amd64

steps:
  - name: security-build
    image: docker.io/owncloudci/drone-docker-buildx:1
    settings:
      build_args_from_env:
        - COLLABORA_TOKEN
      dockerfile: Dockerfile
      output: type=oci,dest=oci/${DRONE_REPO_NAME},tar=false
      repo: registry.owncloud.com/${DRONE_REPO_NAME}/server
    environment:
      COLLABORA_TOKEN:
        from_secret: collabora_token

  - name: security-scan
    image: ghcr.io/aquasecurity/trivy
    commands:
      - trivy -v
      - trivy image --input oci/${DRONE_REPO_NAME}
    environment:
      TRIVY_EXIT_CODE: 1
      TRIVY_IGNORE_UNFIXED: True
      TRIVY_NO_PROGRESS: True
      TRIVY_SEVERITY: HIGH,CRITICAL
      TRIVY_TIMEOUT: 1m
    depends_on:
      - security-build

  - name: changelog
    image: quay.io/thegeeklab/git-chglog
    commands:
      - git fetch -tq
      - git-chglog --no-color --no-emoji ${DRONE_TAG:---next-tag unreleased unreleased}
      - git-chglog --no-color --no-emoji -o CHANGELOG.md ${DRONE_TAG:---next-tag unreleased unreleased}
    depends_on:
      - security-scan

  - name: publish-registry
    image: docker.io/owncloudci/drone-docker-buildx:1
    settings:
      build_args_from_env:
        - COLLABORA_TOKEN
      dockerfile: Dockerfile
      password:
        from_secret: registry_password
      registry: registry.owncloud.com
      repo: registry.owncloud.com/${DRONE_REPO_NAME}/server
      username:
        from_secret: registry_username
    environment:
      COLLABORA_TOKEN:
        from_secret: collabora_token
    when:
      ref:
        - refs/heads/main
        - refs/tags/**
    depends_on:
      - changelog

  - name: release
    image: docker.io/plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      note: CHANGELOG.md
      overwrite: true
      title: ${DRONE_TAG}
    when:
      ref:
        - refs/tags/**
    depends_on:
      - publish-registry

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
type: docker
name: notifications

platform:
  os: linux
  arch: amd64

steps:
  - name: notify
    image: docker.io/plugins/slack
    settings:
      channel:
        from_secret: rocketchat_chat_channel
      webhook:
        from_secret: rocketchat_chat_webhook
    when:
      status:
        - failure

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
  status:
    - success
    - failure

depends_on:
  - container

...
