---
kind: pipeline
name: container

platform:
  os: linux
  arch: amd64

steps:
- name: tags
  image: thegeeklab/docker-autotag
  environment:
    DOCKER_AUTOTAG_FORCE_LATEST: True
    DOCKER_AUTOTAG_IGNORE_PRERELEASE: True
    DOCKER_AUTOTAG_OUTPUT_FILE: .tags
    DOCKER_AUTOTAG_VERSION: ${DRONE_TAG}

- name: dryrun
  image: plugins/docker
  settings:
    build_args_from_env:
    - COLLABORA_TOKEN
    dockerfile: Dockerfile
    dry_run: true
    repo: registry.owncloud.com/${DRONE_REPO_NAME}/server
  environment:
    COLLABORA_TOKEN:
      from_secret: collabora_token
  when:
    ref:
    - refs/pull/**

- name: publish
  image: plugins/docker
  settings:
    build_args_from_env:
    - COLLABORA_TOKEN
    dockerfile: Dockerfile
    password:
      from_secret: registry_password
    registry: registry.owncloud.com
    repo: registry.owncloud.com/${DRONE_REPO_NAME}/server
    username:
      from_secret: registry_username
  environment:
    COLLABORA_TOKEN:
      from_secret: collabora_token
  when:
    ref:
    - refs/heads/main
    - refs/tags/**

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
- name: changelog
  image: thegeeklab/git-chglog
  commands:
  - git fetch -tq
  - git-chglog --no-color --no-emoji ${DRONE_TAG:---next-tag unreleased unreleased}
  - git-chglog --no-color --no-emoji -o CHANGELOG.md ${DRONE_TAG:---next-tag unreleased unreleased}

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**

depends_on:
  - container

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private
  when:
    status:
    - failure

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- release

...
