FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:dc06ba83c6f47fc0a2bca516a9b99f1cf8ef37331fd460f4ca55579a815ee6cb

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="Collabora"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ops/collabora"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ops/collabora"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ops/collabora"

ARG COLLABORA_TOKEN
ARG BUILD_VERSION
ARG GOMPLATE_VERSION
ARG CONTAINER_LIBRARY_VERSION

# renovate: datasource=github-releases depName=hairyhenderson/gomplate
ENV GOMPLATE_VERSION="${GOMPLATE_VERSION:-v3.11.4}"
# renovate: datasource=docker depName=collabora/code
ENV COLLABORA_RAW_VERSION="${BUILD_VERSION:-22.05.10.2.1}"
# renovate: datasource=github-releases depName=owncloud-ops/container-library
ENV CONTAINER_LIBRARY_VERSION="${CONTAINER_LIBRARY_VERSION:-v0.1.0}"

ENV LC_CTYPE=C.UTF-8

ADD overlay /
WORKDIR /opt/cool

RUN microdnf install -y curl gnupg2 ca-certificates openssh-clients microdnf yum-utils tar && \
    curl -SsfL -o /usr/local/bin/gomplate "https://github.com/hairyhenderson/gomplate/releases/download/${GOMPLATE_VERSION}/gomplate_linux-amd64" && \
    curl -SsfL "https://github.com/owncloud-ops/container-library/releases/download/${CONTAINER_LIBRARY_VERSION}/container-library.tar.gz" | tar xz -C / && \
    chmod 755 /usr/local/bin/gomplate && \
    COLLABORA_VERSION=$(echo "$COLLABORA_RAW_VERSION" | cut -d '.' -f 1,2) && \
    echo "Setup Collabora 'v$COLLABORA_VERSION'" && \
    rpm --import "https://www.collaboraoffice.com/repos/CollaboraOnline/${COLLABORA_VERSION}/customer-centos8-${COLLABORA_TOKEN}/repodata/repomd.xml.key" && \
    yum-config-manager --add-repo "https://www.collaboraoffice.com/repos/CollaboraOnline/${COLLABORA_VERSION}/customer-centos8-${COLLABORA_TOKEN}" && \
    microdnf install -y coolwsd collabora-online-brand collaboraoffice-dict* \
      collaboraofficebasis-ar collaboraofficebasis-as collaboraofficebasis-ast \
      collaboraofficebasis-bg collaboraofficebasis-bn-IN \
      collaboraofficebasis-br collaboraofficebasis-ca \
      collaboraofficebasis-calc collaboraofficebasis-ca-valencia \
      collaboraofficebasis-core collaboraofficebasis-cs \
      collaboraofficebasis-cy collaboraofficebasis-da \
      collaboraofficebasis-de collaboraofficebasis-draw \
      collaboraofficebasis-el collaboraofficebasis-en-GB \
      collaboraofficebasis-en-US collaboraofficebasis-es \
      collaboraofficebasis-et collaboraofficebasis-eu \
      collaboraofficebasis-extension-pdf-import collaboraofficebasis-fi \
      collaboraofficebasis-fr collaboraofficebasis-ga \
      collaboraofficebasis-gd collaboraofficebasis-gl \
      collaboraofficebasis-graphicfilter collaboraofficebasis-gu \
      collaboraofficebasis-he collaboraofficebasis-hi \
      collaboraofficebasis-hr collaboraofficebasis-hu \
      collaboraofficebasis-id collaboraofficebasis-images \
      collaboraofficebasis-impress collaboraofficebasis-is \
      collaboraofficebasis-it collaboraofficebasis-ja \
      collaboraofficebasis-km collaboraofficebasis-kn \
      collaboraofficebasis-ko collaboraofficebasis-lt \
      collaboraofficebasis-lv collaboraofficebasis-ml \
      collaboraofficebasis-mr collaboraofficebasis-nb \
      collaboraofficebasis-nl collaboraofficebasis-nn \
      collaboraofficebasis-oc collaboraofficebasis-ooofonts \
      collaboraofficebasis-ooolinguistic collaboraofficebasis-or \
      collaboraofficebasis-pa-IN collaboraofficebasis-pl \
      collaboraofficebasis-pt collaboraofficebasis-pt-BR \
      collaboraofficebasis-ro collaboraofficebasis-ru \
      collaboraofficebasis-sk collaboraofficebasis-sl \
      collaboraofficebasis-sr collaboraofficebasis-sr-Latn \
      collaboraofficebasis-sv collaboraofficebasis-ta \
      collaboraofficebasis-te collaboraofficebasis-tr \
      collaboraofficebasis-uk collaboraofficebasis-vi \
      collaboraofficebasis-writer collaboraofficebasis-zh-CN \
      collaboraofficebasis-zh-TW && \
    chown cool:cool /opt/cool/systemplate/etc/hosts /opt/cool/systemplate/etc/resolv.conf && \
    chown cool:cool /etc/coolwsd && \
    rm -rf /etc/coolwsd/proof_key* && \
    microdnf clean all && \
    rm -rf /tmp/*

EXPOSE 9980

USER 997

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/collabora"]
