#!/usr/bin/env bash

declare -x LC_CTYPE
[[ -z "${LC_CTYPE}" ]] && LC_CTYPE="en_US.UTF-8"

declare -x COLLABORA_PRE_SERVER_PATH
[[ -z "${COLLABORA_PRE_SERVER_PATH}" ]] && COLLABORA_PRE_SERVER_PATH="/etc/pre_server.d"

declare -x COLLABORA_POST_SERVER_PATH
[[ -z "${COLLABORA_POST_SERVER_PATH}" ]] && COLLABORA_POST_SERVER_PATH="/etc/post_server.d"

declare -x COLLABORA_ALLOWED_LANGUAGES
[[ -z "${COLLABORA_ALLOWED_LANGUAGES}" ]] && COLLABORA_ALLOWED_LANGUAGES="de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru"

declare -x COLLABORA_TILE_CACHE_PERSISTENT
[[ -z "${COLLABORA_TILE_CACHE_PERSISTENT}" ]] && COLLABORA_TILE_CACHE_PERSISTENT="true"

declare -x COLLABORA_TILE_CACHE_PATH
[[ -z "${COLLABORA_TILE_CACHE_PATH}" ]] && COLLABORA_TILE_CACHE_PATH=""

declare -x COLLABORA_SYS_TEMPLATE_PATH
[[ -z "${COLLABORA_SYS_TEMPLATE_PATH}" ]] && COLLABORA_SYS_TEMPLATE_PATH="/opt/lool/systemplate"

declare -x COLLABORA_LO_TEMPLATE_PATH
[[ -z "${COLLABORA_LO_TEMPLATE_PATH}" ]] && COLLABORA_LO_TEMPLATE_PATH="/opt/collaboraoffice6.0"

declare -x COLLABORA_CHILD_ROOT_PATH
[[ -z "${COLLABORA_CHILD_ROOT_PATH}" ]] && COLLABORA_CHILD_ROOT_PATH="/opt/lool/child-roots"

declare -x COLLABORA_SERVER_NAME
[[ -z "${COLLABORA_SERVER_NAME}" ]] && COLLABORA_SERVER_NAME=""

declare -x COLLABORA_FILE_SERVER_ROOT_PATH
[[ -z "${COLLABORA_FILE_SERVER_ROOT_PATH}" ]] && COLLABORA_FILE_SERVER_ROOT_PATH="/usr/share/loolwsd"

declare -x COLLABORA_MEMPROPORTION
[[ -z "${COLLABORA_MEMPROPORTION}" ]] && COLLABORA_MEMPROPORTION=""

declare -x COLLABORA_NUM_RESPAWN_CHILDREN
[[ -z "${COLLABORA_NUM_RESPAWN_CHILDREN}" ]] && COLLABORA_NUM_RESPAWN_CHILDREN="1"

declare -x COLLABORA_LOLEAFLET_HTML
[[ -z "${COLLABORA_LOLEAFLET_HTML}" ]] && COLLABORA_LOLEAFLET_HTML="loleaflet.html"

declare -x COLLABORA_LOLEAFLET_LOGGING
[[ -z "${COLLABORA_LOLEAFLET_LOGGING}" ]] && COLLABORA_LOLEAFLET_LOGGING="false"

true
