#!/usr/bin/env bash

declare -x COLLABORA_PER_DOCUMENT_MAX_CONCURRENCY
[[ -z "${COLLABORA_PER_DOCUMENT_MAX_CONCURRENCY}" ]] && COLLABORA_PER_DOCUMENT_MAX_CONCURRENCY="4"

declare -x COLLABORA_PER_DOCUMENT_DOCUMENT_SIGNING_URL
[[ -z "${COLLABORA_PER_DOCUMENT_DOCUMENT_SIGNING_URL}" ]] && COLLABORA_PER_DOCUMENT_DOCUMENT_SIGNING_URL=""

declare -x COLLABORA_PER_DOCUMENT_REDLINING_AS_COMMENT
[[ -z "${COLLABORA_PER_DOCUMENT_REDLINING_AS_COMMENT}" ]] && COLLABORA_PER_DOCUMENT_REDLINING_AS_COMMENT="true"

declare -x COLLABORA_PER_DOCUMENT_IDLE_TIMEOUT
[[ -z "${COLLABORA_PER_DOCUMENT_IDLE_TIMEOUT}" ]] && COLLABORA_PER_DOCUMENT_IDLE_TIMEOUT="3600"

declare -x COLLABORA_PER_DOCUMENT_IDLESAVE_DURATION
[[ -z "${COLLABORA_PER_DOCUMENT_IDLESAVE_DURATION}" ]] && COLLABORA_PER_DOCUMENT_IDLESAVE_DURATION="30"

declare -x COLLABORA_PER_DOCUMENT_AUTOSAVE_DURATION
[[ -z "${COLLABORA_PER_DOCUMENT_AUTOSAVE_DURATION}" ]] && COLLABORA_PER_DOCUMENT_AUTOSAVE_DURATION="300"

declare -x COLLABORA_PER_DOCUMENT_LIMIT_VIRT_MEM
[[ -z "${COLLABORA_PER_DOCUMENT_LIMIT_VIRT_MEM}" ]] && COLLABORA_PER_DOCUMENT_LIMIT_VIRT_MEM="0"

declare -x COLLABORA_PER_DOCUMENT_LIMIT_DATA_MEM
[[ -z "${COLLABORA_PER_DOCUMENT_LIMIT_DATA_MEM}" ]] && COLLABORA_PER_DOCUMENT_LIMIT_DATA_MEM="0"

declare -x COLLABORA_PER_DOCUMENT_LIMIT_STACK_MEM
[[ -z "${COLLABORA_PER_DOCUMENT_LIMIT_STACK_MEM}" ]] && COLLABORA_PER_DOCUMENT_LIMIT_STACK_MEM="8000"

declare -x COLLABORA_PER_DOCUMENT_LIMIT_FILE_SIZE
[[ -z "${COLLABORA_PER_DOCUMENT_LIMIT_FILE_SIZE}" ]] && COLLABORA_PER_DOCUMENT_LIMIT_FILE_SIZE="0"

declare -x COLLABORA_PER_DOCUMENT_LIMIT_NUM_OPEN_FILES
[[ -z "${COLLABORA_PER_DOCUMENT_LIMIT_NUM_OPEN_FILES}" ]] && COLLABORA_PER_DOCUMENT_LIMIT_NUM_OPEN_FILES="0"

declare -x COLLABORA_PER_DOCUMENT_LIMIT_LOAD
[[ -z "${COLLABORA_PER_DOCUMENT_LIMIT_LOAD}" ]] && COLLABORA_PER_DOCUMENT_LIMIT_LOAD="100"

true
