#!/usr/bin/env bash

declare -x COLLABORA_LOGGING_COLOR
[[ -z "${COLLABORA_LOGGING_COLOR}" ]] && COLLABORA_LOGGING_COLOR="true"

declare -x COLLABORA_LOGGING_LEVEL
[[ -z "${COLLABORA_LOGGING_LEVEL}" ]] && COLLABORA_LOGGING_LEVEL="warning"

declare -x COLLABORA_LOGGING_FILE_ENABLE
[[ -z "${COLLABORA_LOGGING_FILE_ENABLE}" ]] && COLLABORA_LOGGING_FILE_ENABLE="false"

declare -x COLLABORA_LOGGING_FILE_PATH
[[ -z "${COLLABORA_LOGGING_FILE_PATH}" ]] && COLLABORA_LOGGING_FILE_PATH="/var/log/loolwsd.log"

declare -x COLLABORA_LOGGING_FILE_ROTATION
[[ -z "${COLLABORA_LOGGING_FILE_ROTATION}" ]] && COLLABORA_LOGGING_FILE_ROTATION="never"

declare -x COLLABORA_LOGGING_FILE_ARCHIVE
[[ -z "${COLLABORA_LOGGING_FILE_ARCHIVE}" ]] && COLLABORA_LOGGING_FILE_ARCHIVE="timestamp"

declare -x COLLABORA_LOGGING_FILE_COMPRESS
[[ -z "${COLLABORA_LOGGING_FILE_COMPRESS}" ]] && COLLABORA_LOGGING_FILE_COMPRESS="true"

declare -x COLLABORA_LOGGING_FILE_PURGE_AGE
[[ -z "${COLLABORA_LOGGING_FILE_PURGE_AGE}" ]] && COLLABORA_LOGGING_FILE_PURGE_AGE="10 days"

declare -x COLLABORA_LOGGING_FILE_PURGE_COUNT
[[ -z "${COLLABORA_LOGGING_FILE_PURGE_COUNT}" ]] && COLLABORA_LOGGING_FILE_PURGE_COUNT="10"

declare -x COLLABORA_LOGGING_FILE_ROTATE_ON_OPEN
[[ -z "${COLLABORA_LOGGING_FILE_ROTATE_ON_OPEN}" ]] && COLLABORA_LOGGING_FILE_ROTATE_ON_OPEN="true"

declare -x COLLABORA_LOGGING_FILE_FLUSH
[[ -z "${COLLABORA_LOGGING_FILE_FLUSH}" ]] && COLLABORA_LOGGING_FILE_FLUSH="false"

declare -x COLLABORA_LOGGING_ANONYMIZE_FILENAMES
[[ -z "${COLLABORA_LOGGING_ANONYMIZE_FILENAMES}" ]] && COLLABORA_LOGGING_ANONYMIZE_FILENAMES="false"

declare -x COLLABORA_LOGGING_ANONYMIZE_USERNAMES
[[ -z "${COLLABORA_LOGGING_ANONYMIZE_USERNAMES}" ]] && COLLABORA_LOGGING_ANONYMIZE_USERNAMES="false"

true
