#!/usr/bin/env bash

declare -x COLLABORA_TRACE_ENABLE
[[ -z "${COLLABORA_TRACE_ENABLE}" ]] && COLLABORA_TRACE_ENABLE="false"

declare -x COLLABORA_TRACE_COMPRESS
[[ -z "${COLLABORA_TRACE_COMPRESS}" ]] && COLLABORA_TRACE_COMPRESS="true"

declare -x COLLABORA_TRACE_SNAPSHOW
[[ -z "${COLLABORA_TRACE_SNAPSHOW}" ]] && COLLABORA_TRACE_SNAPSHOW="false"

declare -x COLLABORA_TRACE_PATH
[[ -z "${COLLABORA_TRACE_PATH}" ]] && COLLABORA_TRACE_PATH=""

declare -x COLLABORA_TRACE_FILTER
[[ -z "${COLLABORA_TRACE_FILTER}" ]] && COLLABORA_TRACE_FILTER=""

declare -x COLLABORA_TRACE_OUTGOING_RECORD
[[ -z "${COLLABORA_TRACE_OUTGOING_RECORD}" ]] && COLLABORA_TRACE_OUTGOING_RECORD="false"

true
