#!/usr/bin/env bash

declare -x COLLABORA_NET_PROTO
[[ -z "${COLLABORA_NET_PROTO}" ]] && COLLABORA_NET_PROTO="all"

declare -x COLLABORA_NET_LISTEN
[[ -z "${COLLABORA_NET_LISTEN}" ]] && COLLABORA_NET_LISTEN="any"

declare -x COLLABORA_NET_SERVICE_ROOT
[[ -z "${COLLABORA_NET_SERVICE_ROOT}" ]] && COLLABORA_NET_SERVICE_ROOT=""

declare -x COLLABORA_NET_FRAME_ANCESTORS
[[ -z "${COLLABORA_NET_FRAME_ANCESTORS}" ]] && COLLABORA_NET_FRAME_ANCESTORS=""

declare -x COLLABORA_NET_POST_ALLOW
[[ -z "${COLLABORA_NET_POST_ALLOW}" ]] && COLLABORA_NET_POST_ALLOW="true"

declare -x COLLABORA_NET_POST_ALLOW_HOSTS
[[ -z "${COLLABORA_NET_POST_ALLOW_HOSTS}" ]] && COLLABORA_NET_POST_ALLOW_HOSTS="127\.0\.0\.1,::1"

true
