#!/usr/bin/env bash

declare -x COLLABORA_SSL_ENABLE
[[ -z "${COLLABORA_SSL_ENABLE}" ]] && COLLABORA_SSL_ENABLE="false"

declare -x COLLABORA_SSL_TERMINATION
[[ -z "${COLLABORA_SSL_TERMINATION}" ]] && COLLABORA_SSL_TERMINATION="false"

declare -x COLLABORA_SSL_CERT_FILE
[[ -z "${COLLABORA_SSL_CERT_FILE}" ]] && COLLABORA_SSL_CERT_FILE="/etc/loolwsd/cert.pem"

declare -x COLLABORA_SSL_KEY_FILE
[[ -z "${COLLABORA_SSL_KEY_FILE}" ]] && COLLABORA_SSL_KEY_FILE="/etc/loolwsd/key.pem"

declare -x COLLABORA_SSL_CA_FILE
[[ -z "${COLLABORA_SSL_CA_FILE}" ]] && COLLABORA_SSL_CA_FILE="/etc/loolwsd/ca-chain.cert.pem"

declare -x COLLABORA_SSL_CIPHER_LIST
[[ -z "${COLLABORA_SSL_CIPHER_LIST}" ]] && COLLABORA_SSL_CIPHER_LIST=""

declare -x COLLABORA_SSL_HPKP_ENABLE
[[ -z "${COLLABORA_SSL_HPKP_ENABLE}" ]] && COLLABORA_SSL_HPKP_ENABLE="false"

declare -x COLLABORA_SSL_HPKP_REPORT_ONLY
[[ -z "${COLLABORA_SSL_HPKP_REPORT_ONLY}" ]] && COLLABORA_SSL_HPKP_REPORT_ONLY="false"

declare -x COLLABORA_SSL_HPKP_MAX_AGE_ENABLE
[[ -z "${COLLABORA_SSL_HPKP_MAX_AGE_ENABLE}" ]] && COLLABORA_SSL_HPKP_MAX_AGE_ENABLE="true"

declare -x COLLABORA_SSL_HPKP_MAX_AGE
[[ -z "${COLLABORA_SSL_HPKP_MAX_AGE}" ]] && COLLABORA_SSL_HPKP_MAX_AGE="1000"

declare -x COLLABORA_SSL_HPKP_REPORT_URI_ENABLE
[[ -z "${COLLABORA_SSL_HPKP_REPORT_URI_ENABLE}" ]] && COLLABORA_SSL_HPKP_REPORT_URI_ENABLE="false"

declare -x COLLABORA_SSL_HPKP_REPORT_URI
[[ -z "${COLLABORA_SSL_HPKP_REPORT_URI}" ]] && COLLABORA_SSL_HPKP_REPORT_URI=""

declare -x COLLABORA_SSL_HPKP_PINS
[[ -z "${COLLABORA_SSL_HPKP_PINS}" ]] && COLLABORA_SSL_HPKP_PINS=""

true
