#!/usr/bin/env bash

declare -x COLLABORA_SECURITY_SECCOMP
[[ -z "${COLLABORA_SECURITY_SECCOMP}" ]] && COLLABORA_SECURITY_SECCOMP="true"

declare -x COLLABORA_SECURITY_CAPABILITIES
[[ -z "${COLLABORA_SECURITY_CAPABILITIES}" ]] && COLLABORA_SECURITY_CAPABILITIES="true"

true
