#!/usr/bin/env bash

declare -x COLLABORA_STORAGE_FILESYSTEM_ALLOW
[[ -z "${COLLABORA_STORAGE_FILESYSTEM_ALLOW}" ]] && COLLABORA_STORAGE_FILESYSTEM_ALLOW="false"

declare -x COLLABORA_STORAGE_WOPI_ALLOW
[[ -z "${COLLABORA_STORAGE_WOPI_ALLOW}" ]] && COLLABORA_STORAGE_WOPI_ALLOW="true"

declare -x COLLABORA_STORAGE_WOPI_MAX_FILE_SIZE
[[ -z "${COLLABORA_STORAGE_WOPI_MAX_FILE_SIZE}" ]] && COLLABORA_STORAGE_WOPI_MAX_FILE_SIZE="0"

declare -x COLLABORA_STORAGE_WOPI_HOSTS_REJECT
[[ -z "${COLLABORA_STORAGE_WOPI_HOSTS_REJECT}" ]] && COLLABORA_STORAGE_WOPI_HOSTS_REJECT=""

declare -x COLLABORA_STORAGE_WOPI_HOSTS_ALLOW
[[ -z "${COLLABORA_STORAGE_WOPI_HOSTS_ALLOW}" ]] && COLLABORA_STORAGE_WOPI_HOSTS_ALLOW="localhost"

declare -x COLLABORA_STORAGE_WEBDAV_ALLOW
[[ -z "${COLLABORA_STORAGE_WEBDAV_ALLOW}" ]] && COLLABORA_STORAGE_WEBDAV_ALLOW="false"

declare -x COLLABORA_STORAGE_WEBDAV_HOSTS_REJECT
[[ -z "${COLLABORA_STORAGE_WEBDAV_HOSTS_REJECT}" ]] && COLLABORA_STORAGE_WEBDAV_HOSTS_REJECT="localhost"

declare -x COLLABORA_STORAGE_WEBDAV_HOSTS_ALLOW
[[ -z "${COLLABORA_STORAGE_WEBDAV_HOSTS_ALLOW}" ]] && COLLABORA_STORAGE_WEBDAV_HOSTS_ALLOW=""

true
