#!/usr/bin/env bash

declare -x COLLABORA_ADMIN_CONSOLE_ENABLE
[[ -z "${COLLABORA_ADMIN_CONSOLE_ENABLE}" ]] && COLLABORA_ADMIN_CONSOLE_ENABLE="true"

declare -x COLLABORA_ADMIN_CONSOLE_ENABLE_PAM
[[ -z "${COLLABORA_ADMIN_CONSOLE_ENABLE_PAM}" ]] && COLLABORA_ADMIN_CONSOLE_ENABLE_PAM="false"

declare -x COLLABORA_ADMIN_CONSOLE_USERNAME
[[ -z "${COLLABORA_ADMIN_CONSOLE_USERNAME}" ]] && COLLABORA_ADMIN_CONSOLE_USERNAME=""

declare -x COLLABORA_ADMIN_CONSOLE_PASSWORD
[[ -z "${COLLABORA_ADMIN_CONSOLE_PASSWORD}" ]] && COLLABORA_ADMIN_CONSOLE_PASSWORD=""

true
